---
title: Understanding weighted regression in the context of exact matching.
author: Suhishan Bhandari
---

*Notes*

 Weight = (Number of parents (treatment) in the subclass)/(Number of Childless Individuals in the subclass)

For e.g. If there are 14 in the treatment and 60 in the control in the same subclass i.e. same cross-covariate sub group, then each person in the control group in that subclass gets the weight of : 14/60 = 0.23

```{r}
data1 <- tibble(
    subclass = sample(c(1:5), 100, replace = TRUE,
    prob = c(0.1, 0.15, 0.15, 0.2, 0.4)),
    id = seq(c(1:100))
)
data2 <- tibble(
    outcome = rbinom(160, 1, prob = 0.7),
    subclass = sample(c(1:5), 160, replace = TRUE,
    prob = c(0.4, 0.2, 0.15, 0.15, 0.1))
)

# Weights
subcount1 <- table(data1$subclass)
subcount2 <- table(data2$subclass)
weights <- subcount1/subcount2

data2$weights <- weights[data2$subclass]

# Non-collapse joining.
joined_df <- data1 |> left_join(data2, by = c("subclass"),
relationship = "many-to-many")

# Compute Mean and then join.
data2_collapsed <- data2 |> group_by(subclass) |> 
    summarize(outcome = mean(outcome), count = n())

joined_collapsed <- data1 |> left_join(data2_collapsed, by = c("subclass"))
```


## Analysis

```{r}
# Weighted Mean
with(joined_df, weighted.mean(outcome, weights))
#summary(lm(outcome ~ 1, data = joined_df, weights = joined_df$weights))
# General Mean
with(joined_df, mean(outcome))
#summary(lm(outcome ~ 1, data = joined_df))
```

*Analysis on Collapsed*


```{r}
with(joined_collapsed, mean(outcome))
summary(lm(outcome ~ 1, data = joined_collapsed))
# Weighted by counts
with(joined_collapsed, weighted.mean(outcome, count))
summary(lm(outcome ~ 1, data = joined_collapsed, 
weights = joined_collapsed$count))
```



## Why do the means differ?


```{r}
# Normal Mean without considering weights.
joined_df |> filter(id %in% c(1:2)) |> summarize(mean(outcome))

# Mean by considering weights.
joined_df |> filter(id %in% c(1:2)) |> summarize(weighted.mean(outcome, weights))
```